
CREATE TABLE clustertable (
  Rank INT(10) NOT NULL,
  Clsuter_ID VARCHAR(5) NOT NULL,
  NodeN INT(10) NOT NULL,
  SpeciesN INT(10) NOT NULL,
  Mean_edge FLOAT(10) NOT NULL,
  LinkN INT(10) NOT NULL,
  TripletN INT(10) NOT NULL,
  Score FLOAT(10) NOT NULL,
  PRIMARY KEY (Clsuter_ID)
);

LOAD DATA LOCAL INFILE  '/work1/home/peiyu/FunCoreTest/FunCore/DB/rank.csv'
INTO TABLE clustertable
CHARACTER SET UTF8
FIELDS TERMINATED BY ',' 
IGNORE 1 ROWS;

CREATE TABLE sequencetable (
  sp VARCHAR(255) NOT NULL,
  Clsuter_ID VARCHAR(255) NOT NULL,
  Genus VARCHAR(255) NOT NULL,
  Speices VARCHAR(255) NOT NULL,
  Seq_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (Seq_ID),
  FOREIGN KEY (Clsuter_ID) REFERENCES clustertable(Clsuter_ID)
);

LOAD DATA LOCAL INFILE  '/work1/home/peiyu/FunCoreTest/FunCore/DB/Sequence.csv'
INTO TABLE sequencetable
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
ENCLOSED by '"' 
IGNORE 1 ROWS;

CREATE TABLE functiontable (
  Seq_ID VARCHAR(255) NOT NULL,
  GO_Function VARCHAR(255) NOT NULL,
  GO_Acc VARCHAR(255) NOT NULL,
  GO_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (Seq_ID)
);

LOAD DATA LOCAL INFILE  '/work1/home/peiyu/FunCoreTest/FunCore/DB/Function.csv'
INTO TABLE functiontable
CHARACTER SET UTF8
FIELDS TERMINATED BY ','
ENCLOSED by '"' 
IGNORE 1 ROWS;

CREATE TABLE fastaetable (
  Seq_ID VARCHAR(255) NOT NULL,
  Seq VARCHAR(255) NOT NULL,
  PRIMARY KEY (Seq_ID)
);

LOAD DATA LOCAL INFILE  '/work1/home/peiyu/FunCoreTest/FunCore/DB/Fasta.csv'
INTO TABLE fastaetable
CHARACTER SET UTF8
FIELDS TERMINATED BY ',';